server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: chaitanyakatore
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
